spring:
  application:
    name: gateway-server
  cloud:
    config:
      uri: http://localhost:8071
  config:
    import: "configserver:"

  main:
    web-application-type: reactive
server:
  port: 8770