version: '3.8'

services:
  licensingservice:
    image: ostock/license-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
#      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
    networks:
      backend:
        aliases:
          - "licenseservice"
networks:
  backend:
    driver: bridge