spring:
  cloud:
    config:
      server:
        vault:
          port: 8200
          host: 127.0.0.1
          kv-version: 2
        bootstrap: true
  application:
    name: configserver
  profiles:
    active: vault # This must be there.

server:
  port: 8071
