server:
  port: 8071
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        vault:
          port: 8200
          host: 127.0.0.1
          kv-version: 2
#        native:
#          search-locations: classpath:/config
#        git:
          # Using file
#          uri: file:////home/olakunle/Folders/spring/My-Spring-Projects/optimal-growth-project/configuration-server/src/main/resources/config/git-localconfig-repo
          # Using GIT
#                  uri: https://github.com/ihuaylupo/config
#                  search-paths: licensing-service
encrypt:
  key: olakunlebalogun247
