server:
  port: 8071
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        #        bootstrap: true
        native:
          search-locations: classpath:/config/{application}
#          search-locations: file: ///home/olakunle/Folders/spring/My-Spring-Projects/optimal-growth-project/configuration-server/src/main/resources/config