#### SERVER PORT ####
server:
  port: 8081

#### DATASOURCE MANAGEMENT ####
spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ostock

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ### EUREKA MANAGEMENT ####
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

      ### ACTUATOR MANAGEMENT ###
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true