#spring:
#  application:
#    name: "organization-service"
#  profiles:
#    active: dev
#  cloud:
#    config:
#      uri: http://localhost:8071
#  config:
#    import: "configserver:"
---

spring:
  application:
    name: organization-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8071
#      uri: http://configserver:8071
  config:
    import: "configserver:"
