#spring:
#  application:
#    name: "eureka-server"
#  cloud:
#    config:
#      uri: "http://localhost:8071"
#
#  config:
#    import=configserver:
##    loadbalancer:
##      enabled: false
---
spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://configserver:8071
#    loadbalancer:
#      ribbon:
#        enabled: false