spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://localhost:8071
      fail-fast: true

  config:
    import: "configserver:"
    #    loadbalancer:
#      enabled: false

